name: Check scamplepy
on: push

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and format
        uses: astral-sh/ruff-action@v3

  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Analyze types
        run: uv run --module pyright

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Run tests
        run: uv run --module pytest
